# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class matrix < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/Y-Square-T3/matrix"
  version "1.6.3"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Y-Square-T3/matrix/releases/download/v1.6.3/matrix-darwin-x64.zip"
      sha256 "f92d8928e129af41fb9b09aa970bfa9a019498ad0fabcd2c792cc625984dfc52"

      def install
        bin.install "matrix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Y-Square-T3/matrix/releases/download/v1.6.3/matrix-darwin-arm64.zip"
      sha256 "99b3770c82d923c3b4222d26684ec1ba2200cda48bda0987032c4c54f2ecc367"

      def install
        bin.install "matrix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Square-T3/matrix/releases/download/v1.6.3/matrix-linux-x64.tar.gz"
      sha256 "ee0a0d9bdc7840180ac17a830f8167a72692e41745a4dc2e381f2d15a58cc387"
      def install
        bin.install "matrix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Square-T3/matrix/releases/download/v1.6.3/matrix-linux-arm64.tar.gz"
      sha256 "073e524783b5fb00b95574f758a40fa8f70aaa034897c8d6d708b8f0e6450678"
      def install
        bin.install "matrix"
      end
    end
  end
end

